name: Purge image cache

on:
  schedule:
    - cron: '34 18 * * */7'

permissions: {}

jobs:
  purge:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: >
          curl -sL "https://github.com/${GITHUB_REPOSITORY}" |
          grep -oE '<img src="https?://camo.githubusercontent.com/[^"]+' |
          sed -e 's/<img src="//' |
          xargs -r -I '{}' curl -sX PURGE '{}'
